lib: allow unused import for ffi-testing feat
Running `cargo clippy-ci` using Rust 1.75 fails:

```
error: unused import: `tests::ffi::*`
  --> src/lib.rs:28:9
   |
28 | pub use tests::ffi::*;
   |         ^^^^^^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unused_imports)]`
```

This commit adds a `allow(unused_imports)` gated on the same
`ffi-testing` feature that the `pub use` statement is conditional upon.